// Styles/WasteDetection.js
import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  contentContainer: {
    paddingBottom: 30,
  },
  backButton: {
    padding: 10,
    marginTop: 40,
    marginLeft: 10,
  },
  backButtonText: {
    fontSize: 16,
    color: "#0077b6",
    fontWeight: "600",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 10,
    color: "#2d3748",
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "#718096",
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 15,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  actionButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    minWidth: 120,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cameraButton: {
    backgroundColor: "#0077b6",
  },
  galleryButton: {
    backgroundColor: "#00b4d8",
  },
  detectButton: {
    backgroundColor: "#2E8B57",
    paddingVertical: 15,
    marginHorizontal: 20,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  imageSection: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2d3748",
    marginBottom: 10,
  },
  imageContainer: {
    alignItems: "center",
  },
  imageWrapper: {
    position: "relative",
    borderRadius: 15,
    overflow: "hidden",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  previewImage: {
    borderRadius: 15,
  },
  boundingBox: {
    position: "absolute",
    borderWidth: 2,
    borderRadius: 8,
  },
  labelBox: {
    position: "absolute",
    top: -25,
    left: 0,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  labelText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  detectSection: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  loadingContainer: {
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    color: "#718096",
    fontSize: 14,
  },
  resultsSection: {
    marginHorizontal: 20,
    gap: 15,
  },
  classificationCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2d3748",
    marginBottom: 15,
    textAlign: "center",
  },
  classificationBadge: {
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
  },
  classificationText: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 5,
  },
  confidenceText: {
    color: "white",
    fontSize: 14,
    opacity: 0.9,
  },
  compositionCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  compositionItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  compositionLabel: {
    width: 120,
    fontSize: 12,
    color: "#718096",
    fontWeight: "600",
  },
  progressBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: "#e2e8f0",
    borderRadius: 4,
    marginHorizontal: 10,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    borderRadius: 4,
  },
  percentageText: {
    width: 40,
    fontSize: 12,
    fontWeight: "bold",
    color: "#2d3748",
    textAlign: "right",
  },
  materialsCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  materialItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  materialInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  materialDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
  },
  materialName: {
    fontSize: 14,
    color: "#2d3748",
    fontWeight: "500",
  },
  materialConfidence: {
    fontSize: 14,
    color: "#718096",
    fontWeight: "600",
  },
  objectsCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  objectItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f1f1",
  },
  objectInfo: {
    flex: 1,
  },
  objectLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3748",
    marginBottom: 4,
  },
  objectDetails: {
    fontSize: 12,
    color: "#718096",
  },
  arrow: {
    fontSize: 18,
    color: "#cbd5e0",
  },
  tipsCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tipItem: {
    flexDirection: "row",
    marginBottom: 10,
    alignItems: "flex-start",
  },
  tipBullet: {
    fontSize: 16,
    color: "#2E8B57",
    marginRight: 10,
    marginTop: 2,
  },
  tipText: {
    flex: 1,
    fontSize: 14,
    color: "#4a5568",
    lineHeight: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 25,
    width: "80%",
    maxWidth: 350,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2d3748",
    marginBottom: 20,
    textAlign: "center",
  },
  detailItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f1f1",
  },
  detailLabel: {
    fontSize: 16,
    color: "#718096",
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 16,
    color: "#2d3748",
    fontWeight: "600",
  },
  closeButton: {
    backgroundColor: "#0077b6",
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  closeButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
});